const ORIGIN = "http://localhost:8000";
const API = `${ORIGIN}/api/v1`;
const app = document.querySelector("#app");
const extra = {
  "project-central-library": { field: "公共施設改修", todo: "設計資料の確認", csv: 1 },
  "project-river-monitoring": { field: "環境調査", todo: "観測項目の整理", csv: 0 },
};
const state = { view: location.hash.replace("#", "") || "dashboard", projects: [], id: null, project: null, docs: [], threads: [], threadId: null, tab: "overview", previewId: null, leftOpen: true, chatWidth: Number(localStorage.getItem("portal-chat-width")) || 380, mode: "通常", notice: "", health: null };

const esc = (v) => String(v ?? "").replace(/[&<>'"]/g, (c) => ({"&":"&amp;","<":"&gt;",">":"&lt;","'":"&#39;",'"':"&quot;"}[c]));
const date = (v) => v ? new Intl.DateTimeFormat("ja-JP", { dateStyle:"short", timeStyle:"short" }).format(new Date(v)) : "-";
const bytes = (v) => v < 1024 ? `${v} B` : `${(v / 1024).toFixed(1)} KB`;
const status = (v) => ({planning:"計画中",active:"進行中",completed:"完了",on_hold:"保留"}[v] || v);
const docStatus = (v) => ({uploaded:"登録済み",processing:"処理中",ready:"利用可能",failed:"失敗"}[v] || v);
const ragStatus = (v) => ({not_started:"未開始",pending:"同期準備中",processing:"同期中",synced:"同期済み",failed:"同期失敗"}[v] || v);
const info = (id) => extra[id] || { field:"未設定", todo:"TODO未登録", csv:0 };

async function errorOf(response) { let message = `HTTP ${response.status}`; try { message = (await response.json()).error?.message || message; } catch (_) {} const e = new Error(message); e.status = response.status; return e; }
async function get(path) { const r = await fetch(`${API}${path}`); if (!r.ok) throw await errorOf(r); return r.json(); }
async function post(path, body) { const r = await fetch(`${API}${path}`, { method:"POST", headers:{"Content-Type":"application/json"}, body: JSON.stringify(body) }); if (!r.ok) throw await errorOf(r); return r.json(); }
async function getHealth() { const r = await fetch(`${ORIGIN}/health`); if (!r.ok) throw await errorOf(r); return r.json(); }
function set(html) { app.innerHTML = html; bind(); }
function current(project) { return project.id === state.id ? " selected" : ""; }

function projectItem(project, dashboard = false) {
  const pending = project.document_count - (project.id === state.id ? state.project?.rag_synced_document_count || 0 : 0);
  return `<button class="project-item${current(project)}" data-project="${project.id}"><span class="initial">${esc(project.name).slice(0,1)}</span><span class="project-main"><strong>${esc(project.name)}</strong><small>${esc(project.code)} · ${status(project.status)}</small>${dashboard ? `<small>${esc(info(project.id).field)} / ${esc(project.location)}</small>` : `<small>更新 ${date(project.updated_at)}</small>`}</span><span class="project-badge">${dashboard ? `未処理 ${Math.max(0,pending)} / TODO` : status(project.status)}</span></button>`;
}
function headerState() { document.querySelectorAll(".global-nav button").forEach((b) => b.classList.toggle("current", b.dataset.view === state.view)); }
function dashboard() {
  const p = state.project;
  const overview = state.projects.length ? `${state.projects.filter((x)=>x.status === "active").length} 件` : "-";
  return `<section class="dashboard"><section class="dash-left"><div class="page-title"><p>ダッシュボード</p><h1>業務の全体概要</h1></div><dl class="summary-metrics"><div><dt>稼働中案件</dt><dd>${overview}</dd></div><div><dt>資料件数</dt><dd>${state.projects.reduce((n,x)=>n+x.document_count,0)} 件</dd></div><div><dt>注意事項</dt><dd>同期状態を確認</dd></div></dl><section><h2>案件一覧</h2><div class="dashboard-projects">${state.projects.map((x)=>projectItem(x,true)).join("") || `<p>案件がありません。</p>`}</div></section><section><h2>最近追加された資料</h2>${p?.recent_documents?.length ? `<ul class="recent">${p.recent_documents.map((x)=>`<li>${esc(x.name)} <small>${date(x.updated_at)}</small></li>`).join("")}</ul>` : `<p class="empty">選択案件の最近の資料はありません。</p>`}</section></section><section class="dash-detail">${p ? dashboardDetail(p) : `<div class="empty-panel">案件を選択してください。</div>`}</section></section>`;
}
function dashboardDetail(p) { const x=info(p.id); return `<div class="page-title"><p>${esc(p.code)}</p><h1>${esc(p.name)}</h1><span class="status ${p.status}">${status(p.status)}</span></div><dl class="detail-grid"><div><dt>分野</dt><dd>${esc(x.field)}</dd></div><div><dt>所在地</dt><dd>${esc(p.location)}</dd></div><div><dt>期間</dt><dd>${esc(p.period)}</dd></div><div><dt>資料 / PDF / CSV</dt><dd>${p.document_count} / 0 / ${x.csv}</dd></div><div><dt>スレッド</dt><dd>${state.threads.length}</dd></div></dl><h2>案件概要</h2><p>${esc(p.overview)}</p><h2>最近の更新</h2><p>${date(p.updated_at)}</p><button class="button" data-view="projects">案件一覧画面で開く</button>`; }
function projectPane() { return `<aside class="project-pane ${state.leftOpen ? "" : "closed"}"><button class="collapse" data-action="toggle-left" title="案件一覧を開閉">${state.leftOpen ? "‹" : "›"}</button>${state.leftOpen ? `<div class="pane-head"><h2>案件一覧</h2><button class="minor" data-future="新規案件登録">＋ 新規</button></div><input id="project-filter" placeholder="案件を検索" aria-label="案件を検索"><select id="status-filter"><option value="">全状態</option><option value="active">進行中</option><option value="planning">計画中</option></select><div id="project-items">${state.projects.map((p)=>projectItem(p)).join("")}</div>` : ""}</aside>`; }
function tabs() { const main=[["overview","概要"],["materials","資料"],["pdf","PDF"],["csv","CSV"]], admin=[["comments","コメント"],["knowledge","ナレッジ"],["members","メンバー"],["operations","運用メモ"],["jobs","成果物・ジョブ"]]; const all=[...main,...admin]; if(state.previewId){const d=state.docs.find((x)=>x.id===state.previewId);if(d)all.splice(3,0,["preview",d.filename]);} return `<nav class="tabs"><span class="tab-group">${all.slice(0,4).map(tab).join("")}</span><span class="tab-group advanced">${all.slice(4).map(tab).join("")}</span></nav>`; }
function tab([id,label]) { return `<button class="tab ${state.tab===id?"active":""}" data-tab="${id}">${esc(label)}</button>`; }
function metric(name,value){return `<div><dt>${name}</dt><dd>${value}</dd></div>`;}
function overview() { const p=state.project,x=info(p.id); return `<section class="panel"><div class="sticky-project"><div><p>${esc(p.code)}</p><h1>${esc(p.name)}</h1></div><span class="status ${p.status}">${status(p.status)}</span></div><dl class="metrics">${metric("分野",esc(x.field))}${metric("場所",esc(p.location))}${metric("期間",esc(p.period))}${metric("資料",`${p.document_count}件`)}${metric("PDF", "0件")}${metric("CSV",`${x.csv}件`)}${metric("スレッド",`${state.threads.length}件`)}${metric("進行中TODO",esc(x.todo))}</dl><h2>説明</h2><p>${esc(p.overview)}</p><h2>最近の更新</h2><p>${date(p.updated_at)}</p></section>`; }
function materialRows(kind) { const docs=state.docs.filter((d)=>kind === "pdf" ? d.filename.toLowerCase().endsWith(".pdf") : !d.filename.toLowerCase().endsWith(".pdf")); if(!docs.length)return `<p class="empty">${kind === "pdf" ? "PDF資料" : "資料"}がありません。</p>`; return `<div class="material-layout"><div class="material-list">${docs.map((d)=>`<article class="material-item ${state.previewId===d.id?"selected":""}"><button data-preview="${d.id}" class="material-open"><strong>${esc(d.filename)}</strong><small>v1 · ${date(d.created_at)} · ${esc(d.uploaded_by)}</small><small>${docStatus(d.status)} / RAG ${ragStatus(d.rag_sync_status)}</small></button>${d.rag_sync_status === "synced" ? `<small class="sync-label">同期済み</small>` : `<button class="minor" data-sync="${d.id}">${d.rag_sync_status === "failed" ? "同期を再実行" : "Knowledge同期"}</button>`}</article>`).join("")}</div><div class="material-preview"><strong>プレビュー</strong><p>資料を選択するとここに表示します。</p></div></div>`; }
function materials() { return `<section class="panel"><div class="panel-title"><div><h1>資料</h1><p>会話しながら育てるMarkdown作業資料。</p></div><button class="minor" data-future="資料作成">＋ 新規作成</button></div><div class="todo-strip"><strong>主レーン: 進行中</strong><span>未着手</span><span>検証中</span><span>完了</span><span>保留</span></div>${materialRows("materials")}</section>`; }
function pdf() { return `<section class="panel"><div class="panel-title"><div><h1>PDF</h1><p>PDF資料とRAG同期状態を管理します。</p></div></div><form id="upload-form" class="upload"><input type="file" name="file" accept=".pdf,.txt,.md,.csv" required><button class="button">アップロード</button><span id="upload-state">最大10MB</span></form>${materialRows("pdf")}</section>`; }
function csv(){return future("CSV", "CSV一覧、表形式プレビュー、列名・行番号、Text-to-SQL結果をここに表示します。", "CSV取込・解析は未実装です。AI回答の対象行ハイライト用イベント境界を保持します。");}
function future(title,description,body){return `<section class="panel"><div class="panel-title"><div><h1>${title}</h1><p>${description}</p></div><span class="coming">未実装</span></div><div class="future">${body}</div></section>`;}
function preview(){const d=state.docs.find((x)=>x.id===state.previewId);if(!d)return pdf();return `<section class="panel"><div class="panel-title"><div><p>動的タブ</p><h1>${esc(d.filename)}</h1></div><button class="minor" data-tab="pdf">PDFへ戻る</button></div><div class="preview"><span>▧</span><strong>資料プレビュー領域</strong><p>PDF.js接続後、根拠ページをここへ表示します。</p></div></section>`;}
function center(){if(!state.project)return `<section class="empty-panel">案件を選択してください。</section>`;let body={overview,materials,pdf,csv,preview,comments:()=>future("コメント","進捗共有と時系列表示。","コメントAPIを追加予定です。"),knowledge:()=>future("ナレッジ","FAQと再利用可能なQ&A。","Knowledge同期の管理画面を追加予定です。"),members:()=>future("メンバー","manager / member / viewerの将来境界。","正式なACL実装後に有効化します。"),operations:()=>future("運用メモ","README / AGENTS / TODO相当の案件文脈。","版管理付きMarkdownを追加予定です。"),jobs:()=>future("成果物・ジョブ","長時間処理の状態、結果、失敗、再実行。","ジョブ基盤実装後に有効化します。")}[state.tab]||overview;return `<section class="center-pane">${tabs()}${body()}</section>`;}
function chat(){const p=state.project;if(!p)return `<aside class="chat-pane"><p>案件を選択してください。</p></aside>`;const thread=state.threads.find((x)=>x.id===state.threadId);const ready=p.openwebui_knowledge_id&&p.rag_synced_document_count>0;const messages=thread?.messages?.length?thread.messages.map((m)=>`<article class="msg ${m.role}"><strong>${m.role==="assistant"?"AI":"あなた"}</strong><p>${esc(m.content)}</p>${m.citations?.length?`<div class="citations">${m.citations.map((c)=>`<button data-citation="${esc(c.reference||"")}">根拠: ${esc(c.source_name)}</button>`).join("")}</div>`:""}</article>`).join(""):`<div class="empty">スレッドを選択するか、新規チャットを開始してください。</div>`;return `<aside class="chat-pane"><header><div><p>選択案件専用AIチャット</p><h2>${esc(p.name)}</h2><small>モデル: gemma4:e2b / ${state.health?.open_webui_client||"mock"}</small></div></header><div class="threadbar"><select id="thread-select"><option value="">スレッドを選択</option>${state.threads.map((t)=>`<option value="${t.id}" ${t.id===state.threadId?"selected":""}>${esc(t.title)}</option>`).join("")}</select><button class="minor" data-action="new-thread">＋ 新規</button><button class="minor" disabled>削除</button></div><div class="quick"><button data-quick="データ集計">データ集計</button><button data-quick="資料抽出">資料抽出</button><button data-quick="文脈総括">文脈総括</button></div>${ready?"":`<div class="warning">RAGに利用できる資料がありません。<button data-tab="pdf">PDFでKnowledge同期を実行</button></div>`}<div class="messages">${messages}</div><details><summary>処理詳細</summary><p>案件Knowledge、同期済み資料、回答モードを確認します。</p></details><form id="chat-form" class="composer"><p id="chat-state">${ready?"回答待機中":"資料同期後に送信できます"}</p><div><select id="mode"><option>通常</option><option>図解</option><option>報告書</option><option>CSV化</option><option>フル思考</option></select><textarea id="chat-input" placeholder="案件について質問してください" ${ready&&state.threadId?"":"disabled"}></textarea></div><footer><button class="minor" type="button" disabled>送信停止</button><button class="button" ${ready&&state.threadId?"":"disabled"}>送信</button></footer></form></aside>`;}
function workspace(){return `<section id="workspace" class="workspace" style="--chat-width:${state.chatWidth}px">${projectPane()}${center()}<div id="resize" class="resize" title="チャット幅を調整"></div>${chat()}</section>`;}
function search(){return `<section class="search-screen"><div class="page-title"><p>資料検索</p><h1>案件横断の発見・比較・参照</h1></div><form class="search-form"><input placeholder="キーワードで検索"><select><option>全案件</option></select><select><option>全分野</option></select><select><option>全資料種別</option></select><button class="button" type="button">検索</button></form><div class="search-grid"><section><h2>地図・位置情報</h2><div class="map-placeholder">位置情報表示領域</div></section><section><h2>検索結果一覧</h2><p class="empty">検索API実装後に資料一覧を表示します。</p></section><section><h2>資料プレビュー</h2><div class="preview">PDFプレビュー領域</div></section></div></section>`;}
function render(){headerState();set(state.view==="dashboard"?dashboard():state.view==="projects"?workspace():search());}
async function select(id){state.id=id;state.tab="overview";state.previewId=null;state.threadId=null;render();try{const [p,d,t,h]=await Promise.all([get(`/projects/${id}`),get(`/projects/${id}/documents`),get(`/projects/${id}/chat-threads`),getHealth()]);state.project=p;state.docs=d.items;state.threads=t.items;state.health=h;render();}catch(e){state.notice=e.message;render();}}
async function upload(e){e.preventDefault();const form=e.currentTarget, label=document.querySelector("#upload-state");label.textContent="アップロード中…";try{const r=await fetch(`${API}/projects/${state.id}/documents`,{method:"POST",body:new FormData(form)});if(!r.ok)throw await errorOf(r);await select(state.id);}catch(x){label.textContent=`失敗: ${x.message}`;}}
async function thread(){try{const t=await post(`/projects/${state.id}/chat-threads`,{title:"新規チャット"});state.threads=[t,...state.threads];state.threadId=t.id;render();}catch(e){state.notice=e.message;render();}}
async function loadThread(id){const t=await get(`/projects/${state.id}/chat-threads/${id}`);state.threads=state.threads.map(x=>x.id===id?t:x);render();}
async function send(e){e.preventDefault();const input=document.querySelector("#chat-input"), label=document.querySelector("#chat-state");label.textContent="生成中…";try{const t=await post(`/projects/${state.id}/chat-threads/${state.threadId}/messages`,{content:input.value,model_id:"gemma4:e2b"});state.threads=state.threads.map(x=>x.id===t.id?t:x);render();}catch(x){label.textContent=`失敗: ${x.message}`;}}
async function syncDoc(id){state.notice="Knowledge同期中…";render();try{await post(`/projects/${state.id}/documents/${id}/sync`,{});await select(state.id);}catch(e){state.notice=`同期失敗: ${e.message}`;render();}}
function citation(ref){const d=state.docs.find(x=>x.id===ref||x.openwebui_file_id===ref);state.previewId=d?.id||null;state.tab=d?.filename.toLowerCase().endsWith(".pdf")?"preview":"materials";state.notice=d?`根拠資料「${d.filename}」を開きました。`:"根拠資料は資料一覧で確認してください。";render();}
function resize(e){const start=e.clientX,initial=state.chatWidth;const move=(x)=>{state.chatWidth=Math.max(320,Math.min(640,initial-(x.clientX-start)));document.querySelector("#workspace")?.style.setProperty("--chat-width",`${state.chatWidth}px`);};const up=()=>{localStorage.setItem("portal-chat-width",state.chatWidth);window.removeEventListener("pointermove",move);};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up,{once:true});}
function bind(){document.querySelectorAll("[data-project]").forEach(x=>x.onclick=()=>select(x.dataset.project));document.querySelectorAll("[data-view]").forEach(x=>x.onclick=()=>{state.view=x.dataset.view;location.hash=state.view;render();});document.querySelectorAll("[data-tab]").forEach(x=>x.onclick=()=>{state.tab=x.dataset.tab;render();});document.querySelectorAll("[data-preview]").forEach(x=>x.onclick=()=>{state.previewId=x.dataset.preview;state.tab="preview";render();});document.querySelectorAll("[data-sync]").forEach(x=>x.onclick=()=>syncDoc(x.dataset.sync));document.querySelectorAll("[data-citation]").forEach(x=>x.onclick=()=>citation(x.dataset.citation));document.querySelector('[data-action="toggle-left"]')?.addEventListener("click",()=>{state.leftOpen=!state.leftOpen;render();});document.querySelector('[data-action="new-thread"]')?.addEventListener("click",thread);document.querySelector("#thread-select")?.addEventListener("change",e=>{state.threadId=e.target.value||null;if(state.threadId)loadThread(state.threadId);else render();});document.querySelector("#upload-form")?.addEventListener("submit",upload);document.querySelector("#chat-form")?.addEventListener("submit",send);document.querySelector("#resize")?.addEventListener("pointerdown",resize);document.querySelector("#resize")?.addEventListener("dblclick",()=>{state.chatWidth=380;localStorage.setItem("portal-chat-width",380);render();});document.querySelector("#project-filter")?.addEventListener("input",e=>{const q=e.target.value.toLowerCase();document.querySelectorAll(".project-item").forEach(x=>x.hidden=!x.textContent.toLowerCase().includes(q));});document.querySelectorAll("[data-future]").forEach(x=>x.onclick=()=>alert(`${x.dataset.future}は今後実装します。`));document.querySelectorAll("[data-quick]").forEach(x=>x.onclick=()=>{const i=document.querySelector("#chat-input");if(i){i.value=x.dataset.quick;i.focus();}});}
async function boot(){try{state.projects=(await get("/projects")).items;if(state.projects.length)await select(state.projects[0].id);else render();}catch(e){set(`<section class="fatal"><h1>読み込みに失敗しました</h1><p>${esc(e.message)}</p></section>`);}}
window.addEventListener("hashchange",()=>{const v=location.hash.replace("#","");if(["dashboard","projects","search"].includes(v)&&v!==state.view){state.view=v;render();}});boot();
